version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5000"
    volumes:
      - .:/app
      - shopping-data:/app/instance
    environment:
      FLASK_ENV: development

volumes:
  shopping-data:
